---
- name: 'Occopus Credentials: Load the credentials from the playbook'
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: config

- name: 'Security Credentials: Load the credentials and security settings from the playbook'
  include_vars:
    file: "{{ micado_cred_path  }}"
    name: security

- name: Copy config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'user_data/auth_data_credential_manager.csv.j2', dest: '/var/lib/micado/credman/config/provisioning.csv'}
    - { src: 'user_data/user_data_zorp.env.j2', dest: '/var/lib/micado/zorp/config/user_data_zorp.env'}
    - { src: 'micado/micado-manifest.yml.j2', dest: '/var/lib/micado/micado-manifest.yml'}
    - { src: 'micado/cadvisor.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cadvisor.yaml'}
    - { src: 'micado/nodex.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/nodex.yaml'}
    - { src: 'toscasubmitter/key_config.yml.j2', dest: '/var/lib/micado/toscasubmitter/system/key_config.yml'}
    - { src: 'iptables/iptables.conf.j2', dest: '/etc/iptables.conf'}
    - { src: 'iptables/ip6tables.conf.j2', dest: '/etc/ip6tables.conf'}
    - { src: 'zorp/policy.py.j2', dest: '/var/lib/micado/zorp/config/policy.py'}
    - { src: 'ipsec/ipsec.conf', dest: '/etc/ipsec.conf'}
    - { src: 'grafana/data-dashboards-micado.json.j2', dest: '/var/lib/micado/grafana/data/dashboards/micado.json'}

- name: Copy Occopus config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'worker_node/temp_infrastructure_descriptor.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/infrastructure_descriptor.yaml'}
    - { src: 'user_data/auth_data.yaml.j2', dest: '/var/lib/micado/occopus/data/auth_data.yaml'}
    - { src: 'worker_node/cloud_init_worker.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml'}
  when: enable_occopus

- name: Copy Terraform config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'user_data/auth_data.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/auth_data.yaml'}
    - { src: 'worker_node/cloud_init_worker_tf.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cloud_init_worker_tf.yaml'}
  when: enable_terraform