---
- name: 'Cloud Credentials: Load the credentials from the playbook'
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: config

- name: 'Security Credentials: Load the credentials and security settings from the playbook'
  include_vars:
    file: "{{ micado_cred_path  }}"
    name: security
