---
- name: '(Ansible) Load the cloud credentials from the playbook'
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: config

- name: '(Ansible) Load the security settings from the playbook'
  include_vars:
    file: "{{ micado_cred_path  }}"
    name: security
