---
- name: Enable packet filtering
  service:
    name: iptables
    state: restarted
    enabled: yes

- name: Enable IPv6 packet filtering
  service:
    name: ip6tables
    state: restarted
    enabled: yes

- name: Enable and start MiCADO systemd service
  service:
    name: micado
    state: restarted
    enabled: yes
