---
- name: Ensure Google DNS server
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'

- include: docker-install.yml

- include: kubernetes-install.yml

- include: python-install.yml

- include: micado-core-install.yml

- include: micado-security-install.yml

- include: optimizer-install.yml
  when: not disable_optimizer

- include: occopus-install.yml
  when: enable_occopus

- include: terraform-install.yml
  when: enable_terraform
