---
- name: Downloading docker images
  docker_image:
      name: "{{ item }}"
      source: pull
  loop:
      - "{{ docker_images.redis }}"
      - "{{ docker_images.prometheus }}"
      - "{{ docker_images.alertmanager }}"
      - "{{ docker_images.grafana }}"
      - "{{ docker_images.policykeeper }}"
      - "{{ docker_images.dashboard }}"
      - "{{ docker_images.toscasubmitter }}"
      - "{{ docker_images.credential_manager }}"
      - "{{ docker_images.vault }}"
      - "{{ docker_images.securitypolicymanager }}"
      - "{{ docker_images.crypto_engine }}"
      - "{{ docker_images.iivr }}"
      - "{{ docker_images.zorp }}"

- name: Downloading Image Integrity Verifier container
  docker_image:
      name: "{{docker_images.iivr}}"
      source: pull
  when: intel_cpu

- name: Downloading Optimizer container
  docker_image:
      name: "{{docker_images.optimizer}}"
      source: pull
  when: not disable_optimizer

- name: Downloading Occopus container
  docker_image:
      name: "{{docker_images.occopus}}"
      source: pull
  when: enable_occopus

- name: Downloading Terraform container
  docker_image:
      name: "{{docker_images.terraform}}"
      source: pull
  when: enable_terraform